import = [
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]

opacity = 0.7
blur = true

padding.x = 10
padding.y = 10

decorations = "Buttonless"
option_as_alt = "Both"

[font]

normal.family = "Hack Nerd Font"

size = 15.0

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
